data:
  hdf5_file: /mlodata1/lugeon/dream_data/processed/healthy/dataset_small.h5
  window: 10
  output_type: last_frame
  fraction: 0.1
  batch_size: 64

model:
  name: EncoderDecoder
  kwargs:
    activation_fn: ReLU
    dropout: 0.8
    kernel_dim: 3
    encoding_dim: 1024
    time_filter_dim: 5
    n_time_filters: 64
    n_channels: 5
    image_dim: 32
    n_frames: 9

n_epochs: 100
device: 'cuda:0'
    
loss: 
  name: MSELoss
  kwargs:
    reduction: sum

optim: 
  name: Adam
  kwargs:
    lr: 1.e-2

scheduler:
  enabled: True
  name: ReduceLROnPlateau
  kwargs:
    mode: min
    factor: 0.1 
    patience: 0
    min_lr: 1.e-8
    threshold: 1.e-4
    verbose: True

early_stop:
  enabled: True
  kwargs:
    patience: 2
    delta: 0
    path: 'checkpoint/checkpoint.pt'
    verbose: True


