save_dir: /mlodata1/lugeon/eeg_project/results/transformers/autoencoder_warmup_test

data:
  dset_name: EEG_Image_Batch_Dataset
  dset_kwargs:
    hdf5_file: /mlodata1/lugeon/dream_data/processed/baseline_nrem/dataset.h5
    window: 10
    slide: 5
    shuffle: True
    batch_size: 32
    transforms: null
    return_metadata: True
    output_type: none
    next_frame_index: null
  fraction: 0.1

model:
  name: AdverserialAutoencoder
  kwargs:
    autoencoder_kwargs:
      in_channels: 5
      space_dim: 32
      time_dim: 10
      space_patch_size: 4
      time_patch_size: 2
      emb_size: 512
      masking_ratio: 0.9
      encoder_depth: 8
      decoder_depth: 2
      drop_p: 0.0
    adv_strength: 0.01
    n_adv_classes: 20

n_epochs: 300
reshuffle: False
device: 'cuda:0'
verbose: True
    
loss: 
  name: AdverserialLoss
  kwargs:
    main_loss: MSELoss
    main_loss_kwargs:
      reduction: mean
    adv_loss: CrossEntropyLoss 
    adv_loss_kwargs:
      reduction: mean
  n_losses: 2

optim: 
  name: AdamW
  kwargs:
    lr: 1.e-4

scheduler:
  enabled: True
  name: CosineAnnealingWarmRestarts
  kwargs:
    T_0: 10
    T_mult  : 1 
    verbose: True
  step_value: none
  warmup: 5

early_stop:
  enabled: True
  kwargs:
    patience: 20
    delta: 1.e-4
    path: 'checkpoint.pt'
    verbose: True


