save_dir: /mlodata1/lugeon/eeg_project/results/other_arch/linear

data:
  dset_name: EEG_Image_Batch_Dataset
  dset_kwargs:
    hdf5_file: /mlodata1/lugeon/dream_data/processed/baseline_nrem/dataset_logonly.h5
    window: 10
    slide: 5
    shuffle: True
    batch_size: 32
    transforms: null
    return_metadata: False
    output_type: next_frame
    next_frame_index: 1
  fraction: 0.1

model:
  name: LinearEncoderDecoder
  kwargs:
    dropout: 0.8
    encoding_dim: 512
    n_channels: 5
    image_dim: 32
    n_frames: 10

n_epochs: 201
save_epoch: 20
reshuffle: False
device: 'cuda:0'
verbose: True
    
loss: 
  name: MSELoss
  kwargs:
    reduction: mean
  n_losses: 1

optim: 
  name: AdamW
  kwargs:
    lr: 1.e-5
    weight_decay: 0.01

scheduler:
  enabled: False
  step_value: epoch
  warmup: 5
  name: ReduceLROnPlateau
  kwargs:
    mode: min
    factor: 0.1 
    patience: 15
    min_lr: 1.e-5
    threshold: 1.e-4
    verbose: True

early_stop:
  enabled: False
  kwargs:
    patience: 30
    delta: 0
    path: 'checkpoint.pt'
    verbose: True


