save_dir: /home/lugeon/eeg_project/results/loso_ft/autoencoder_newdrop8_adv05

data:
  dset_name: EEG_Image_Batch_Dataset
  dset_kwargs:
    hdf5_file: /mlodata1/lugeon/dream_data/processed/madison_20sec/dataset_nrem_binary.h5
    window: 10
    slide: 5
    shuffle: True
    batch_size: 32
    transforms: null
    return_metadata: True
    output_type: label
    next_frame_index: null
    exclude_subject: []
  fraction: 0.1

model:
  name: FineTuner
  kwargs:
    result_dir: /home/lugeon/eeg_project/results/transformers/autoencoder_mask9
    encoding_dim: 512
    n_classes: 2
    dropout: 0.8
    adverserial: True
    adv_strength: 0.05
    n_adv_classes: 7
    freeze: False

n_epochs: 200
reshuffle: False
device: 'cuda:0'
verbose: False
    
loss: 
  name: AdverserialLoss
  kwargs:
    weight: [1.45, 0.76]
  n_losses: 2

optim: 
  name: Adam
  kwargs:
    lr: 1.e-5

scheduler:
  enabled: False
  name: ReduceLROnPlateau
  kwargs:
    mode: min
    factor: 0.1 
    patience: 20
    min_lr: 1.e-6
    threshold: 1.e-4
    verbose: True

early_stop:
  enabled: True
  kwargs:
    patience: 200
    delta: 0
    path: 'checkpoint.pt'
    verbose: False


