save_dir: ./result/test

data:
  dset_name: EEG_Image_Batch_Dataset
  dset_kwargs:
    hdf5_file: /mlodata1/lugeon/dream_data/processed/healthy/dataset_small.h5
    window: 21
    slide: 5
    shuffle: True
    batch_size: 16
    transforms: null
    return_subject: False
    output_type: last_frame
  fraction: 0.1

model:
  name: EncoderDecoder
  kwargs:
    activation_fn: ReLU
    dropout: 0.8
    kernel_dim: 3
    encoding_dim: 1024
    time_filter_dim: 5
    n_time_filters: 64
    n_channels: 5
    image_dim: 32
    n_frames: 20

n_epochs: 10_000
device: 'cuda:0'
    
loss: 
  name: MSELoss
  kwargs:
    reduction: mean

optim: 
  name: Adam
  kwargs:
    lr: 1.e-5

scheduler:
  enabled: True
  name: ReduceLROnPlateau
  kwargs:
    mode: min
    factor: 0.1 
    patience: 10
    min_lr: 1.e-8
    threshold: 1.e-4
    verbose: True

early_stop:
  enabled: True
  kwargs:
    patience: 15
    delta: 0
    path: 'checkpoint.pt'
    verbose: True


