save_dir: ./result/transformers/masked_auto_encoder_mask95_drop5

data:
  dset_name: EEG_Image_Batch_Dataset
  dset_kwargs:
    hdf5_file: /home/lugeon/eeg_project/dataset_baseline_nrem.h5
    window: 10
    slide: 5
    shuffle: True
    batch_size: 32
    transforms: null
    return_metadata: False
    output_type: none
    next_frame_index: 4
  fraction: 0.1

model:
  name: MaskedAutoEncoder
  kwargs:
    in_channels: 5
    space_dim: 32
    time_dim: 10
    space_patch_size: 4
    time_patch_size: 2
    emb_size: 512
    masking_ratio: 0.95
    encoder_depth: 8
    decoder_depth: 2
    drop_p: 0.5


n_epochs: 300
reshuffle: True
device: 'cuda:0'
    
loss: 
  name: MSELoss
  kwargs:
    reduction: mean

optim: 
  name: Adam
  kwargs:
    lr: 1.e-4

scheduler:
  enabled: True
  name: ReduceLROnPlateau
  kwargs:
    mode: min
    factor: 0.1 
    patience: 10
    min_lr: 1.e-7
    threshold: 1.e-4
    verbose: True

early_stop:
  enabled: True
  kwargs:
    patience: 20
    delta: 0
    path: 'checkpoint.pt'
    verbose: True


