save_dir: ./result/arch_comparison/next_frame_vgg_maxpool_convdecoder

data:
  dset_name: EEG_Image_Batch_Dataset
  dset_kwargs:
    hdf5_file: /mlodata1/lugeon/dream_data/processed/baseline_nrem/dataset.h5
    window: 10
    slide: 5
    shuffle: True
    batch_size: 128
    transforms: null
    return_metadata: False
    output_type: next_frame
    next_frame_index: 4
  fraction: 0.1

model:
  name: ConvolutionalEncoderDecoder
  kwargs:
    dropout: 0.5
    kernel_dim: 3
    features: vgg
    time_aggregation: maxpool
    time_filter_dim: 5
    time_n_filters: 16
    encoding_dim: 512
    n_channels: 5
    image_dim: 32
    n_frames: 10

n_epochs: 100
reshuffle: True
device: 'cuda:0'
    
loss: 
  name: MSELoss
  kwargs:
    reduction: mean

optim: 
  name: Adam
  kwargs:
    lr: 1.e-4

scheduler:
  enabled: True
  name: ReduceLROnPlateau
  kwargs:
    mode: min
    factor: 0.1 
    patience: 10
    min_lr: 1.e-7
    threshold: 1.e-4
    verbose: True

early_stop:
  enabled: True
  kwargs:
    patience: 20
    delta: 0
    path: 'checkpoint.pt'
    verbose: True


