# Configuration file for processing eeg
root_dir: /mlodata1/lugeon/dream_data/chuv/healthy
read_format: scipy
signal_name: datavr_2min
transpose: True # matrix should be of shape (n_samples x n_electrodes)
output_dir: /mlodata1/lugeon/dream_data/processed/madison_nrem/freq

filter_opts:
  subject_pattern: 'M*'
  data_pattern: '*_NREM_*.mat'
  n_electrodes: 257

bw_power_opts:
  sampling_frequency: 500
  time_period: -1
  time_window: 2
  time_shift: 0.5
  bandwidths:
    - [0, 4] 
    - [4, 8]
    - [8, 13]
    - [13, 32]
    - [32, 100]
