# Configuration file for computing bandwiths power from time signal

root_dir: /mlodata1/lugeon/eeg_dream/_data_/raw/
read_format: scipy # {h5py, scipy}
signal_name: datavr_2min
transpose: True # matrix should be of shape (n_samples x n_electrodes)
output_dir: /mlodata1/lugeon/eeg_dream/_data_/processed/freq

filter_opts:
  subject_pattern: 'M*'
  data_pattern: '*.mat'
  n_electrodes: 257

bw_power_opts:
  sampling_frequency: 500
  time_period: 20
  time_window: 2
  time_shift: 0.5
  bandwidths:
    - [0.5, 4] 
    - [4, 8]
    - [8, 13]
    - [13, 32]
    - [32, 100]
