# Configuration file for creating a H5 dataset from images
root_dir: /mlodata1/lugeon/eeg_dream/_data_/processed/images
output_file: /mlodata1/lugeon/eeg_dream/_data_/processed/dataset.h5
metadata: /mlodata1/lugeon/eeg_dream/_data_/metadata/metadata.txt
subject_pattern: 'M*'