# Configuration file for creating a H5 dataset from images
root_dir: /mlodata1/lugeon/dream_data/processed/madison_20sec/images
output_file: /mlodata1/lugeon/dream_data/processed/madison_20sec/dataset_nrem_binary.h5
metadata: /mlodata1/lugeon/dream_data/chuv/metadata/madison_metadata_nrem_binary.txt
subject_pattern: 'M*'

