# Configuration file for transforming frequencies into images
root_dir: /mlodata1/lugeon/dream_data/processed/healthy/images
output_file: /mlodata1/lugeon/dream_data/processed/healthy/dataset.h5
labels: /mlodata1/lugeon/dream_data/chuv/metadata/healthy_labels_map.txt
subject_pattern: 'H*'

