# Configuration file for transforming frequencies into images
root_dir: /mlodata1/lugeon/eeg_dream/_data_/processed/norm
output_dir: /mlodata1/lugeon/eeg_dream/_data_/processed/images
subject_pattern: 'M*'

e_locs_path: /mlodata1/lugeon/eeg_dream/_data_/metadata/channelcoords.mat
e_locs_read_format: scipy

e_upper_limit:
  x: null
  y: null
  z: null

gen_images_opts:
  n_gridpoints: 32
  normalize: False
  edgeless: False
  interpolation: cubic