# Configuration file for normalizing frequency signal
root_dir: /mlodata1/lugeon/dream_data/processed/healthy/freq
output_dir: /mlodata1/lugeon/dream_data/processed/healthy/norm
subject_pattern: 'H*'

norm_opts:
  log: True
  mode: zscore