# Configuration file to normalize the bandwidths power signal

root_dir: /mlodata1/lugeon/dream_data/processed/madison_nrem_binary/freq
output_dir: /mlodata1/lugeon/dream_data/processed/madison_nrem_binary/norm_cal
subject_pattern: 'M*'

norm_opts:
  log: True
  mode: zscore