# Configuration file to normalize the bandwidths power signal

root_dir: /mlodata1/lugeon/eeg_dream/_data_/processed/freq
output_dir: /mlodata1/lugeon/eeg_dream/_data_/processed/norm
subject_pattern: 'M*'

norm_opts:
  log: True
  mode: none